title: Kranthi Kiran
logo: /assets/img/dp.jpg

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/kranthi-kiran13/">LinkedIn</a> |
  <a href="https://github.com/kranthik13">GitHub</a>
  
  <br>   
  A technology enthusiast working to solve real-world problems and trying to bring a change
  <br>
  </p>

theme: jekyll-theme-minimal
